anguage: node_js
node_js:
  - '14.16.0'

cache:
  directories:
    - 'node_modules'

branches:
  only:
    - main
    
before_install:
  - cd ./docs

install:
  - npm install
  - npm run generate

script:
  - echo "Skipping tests"

before_deploy:
  - cd dist

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_ACCESS_TOKEN
  target-branch: main

after_deploy:
  - cd ..
